### ISSUE TITLE
Doesn't work with android 11

### ISSUE THREAD

**Issue by manishsaini0901** [kodie-artner/AR-RViz#17]

**Comment by kodie-artner** [comment]
I'm not able to test with Android, can you describe the issue?

**Comment by nlamprian** [comment]
It doesn't seem to work with other versions as well.

On my tablet with Android 12, the app crashes. The first time, I got a message that said the app has a bug, and prompted me to clear the cache. After that, it keeps closing after the "made with unity" screen.

On my phone with Android 13, the app appears to be incompatible.

I haven't checked the code yet to know how easy it would be to get involved, but otherwise, I'm available for testing.

**Comment by kodie-artner** [comment]
First thing to do would be to check if your device supports ARCore [Compatible devices](https://developers.google.com/ar/devices). 
To check the error, you can run the app in debug mode while the phone is connected to the computer. [adroid debugging](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html)
Just change the build to android in the build settings and click `build and run`.  
There is likely a settings error as all the packages use are cross compatible (ARFoundations and RosTcpConnector)

**Comment by kodie-artner** [comment]
@nlamprian If you have a compatible Android can you test the following build? https://github.com/kodie-artner/AR-RViz/releases/tag/android-test

**Comment by nlamprian** [comment]
My tablet, sadly, is not compatible, so I give up on that. My phone is (Google Pixel 7 Pro). The test apk is still not installable on the phone.

**Comment by Lorite** [comment]
Hi guys, the Google play app is crashing on startup for Android 13. Maybe it's the same issue as yours.
I built the apk from Unity for my Android 13 phone and everything works as it should, same as in the iOS app. The steps that I followed to fix it in Unity were the following:
- Use a newer version of Unity and update all the packages.
- Click on File -> Build settings -> Player settings -> Other settings -> Configuration:
  - Set Scripting Backend to IL2CPP.
  - Check Target Architectures -> ARM64.
![image](https://github.com/kodie-artner/AR-RViz/assets/1508696/feaa9870-a3c5-48e2-99e7-42f5238d6b39)
Could you please test it and update the app on the Google Play Store? @kodie-artner Thank you!!!

**Comment by kodie-artner** [comment]
@Lorite Thanks for looking into this. I updated the settings and made a new release https://github.com/kodie-artner/AR-RViz/releases/tag/1.1
Can you test this one out? I still don't have any android devices. 
I haven't released it on the Google Play Store since downloading the apk from GitHub is easy enough.

**Comment by Lorite** [comment]
@kodie-artner looks good to me 😁

**Comment by nlamprian** [comment]
Works for me as well 🥳
